#!/bin/sh
arg=""
noparam=1
for i
do
	if [ "$i" = "-c" -a "$noparam" == 1 ]
		then
		 sudo bash ~/.yo/yoconf.sh
		 break
	elif [ "$i" = "-t" -a "$noparam" == 1 ]
		then
		 python ~/.yo/yo.py
		 break
	else
		 noparam=0
	fi
	arg="$arg $i"
done
if [ -n "$arg" ]
then
$arg && python ~/.yo/yo.py
fi
