#!/bin/sh
arg=""
noparam=1
for i
do
	if [ "$i" = "-c" -a "$noparam" == 1 ]
		then
		 sudo bash /usr/share/yo/yoconf.sh
		 break
	elif [ "$i" = "-t" -a "$noparam" == 1 ]
		then
		 python /usr/share/yo/yo.py
		 break
	else
		 noparam=0
	fi
	arg="$arg $i"
done
if [ -n "$arg" ]
then
$arg && python /usr/share/yo/yo.py
fi
